name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sat'

jobs:
  test:
    name: ${{ matrix.distribution }} ${{ matrix.playbook }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - centos-8
          - centos-7
          - fedora-32
          - fedora-31
          - fedora-30
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - debian-10
          - debian-9
          - oraclelinux-8
          - oraclelinux-7
          - amazonlinux-2
          - archlinux-rolling
        playbook:
          - python-3.8
          - python-3.7
          - python-3.6
        exclude:
          - {distribution: "fedora-32", playbook: "python-3.6"}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.51

      - name: Test Ansible role Python
        run: |
          container_id=$(mktemp)

          # Run container and mount ansible role with it
          sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-python:ro diodonfrost/${{ matrix.distribution }}-ansible:latest > "${container_id}"

          # Check syntax
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-python/tests/playbooks/${{ matrix.playbook }}.yml --syntax-check

          # Run ansible playbook
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-python/tests/playbooks/${{ matrix.playbook }}.yml

          # Test indempotence
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-python/tests/playbooks/${{ matrix.playbook }}.yml \
          | grep -q 'changed=0.*failed=0' \
          && (echo 'Idempotence test: pass' && exit 0) \
          || (echo 'Idempotence test: fail' && exit 1)

          # Test role
          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
